# Generated by Django 5.2.1 on 2025-12-10 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_teacheravailability_delete_availableslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Пн'), (1, 'Вт'), (2, 'Ср'), (3, 'Чт'), (4, 'Пт'), (5, 'Сб'), (6, 'Вс')], null=True),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together={('teacher', 'date', 'time', 'weekday')},
        ),
    ]
