# Generated by Django 5.2.1 on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_teacheravailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbooking',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Регулярный урок'),
        ),
    ]
