"""
Django settings for maxschool project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
from urllib.parse import unquote, urlparse



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file():
    """
    Load .env from project root or app root.
    Uses python-dotenv when available, with a lightweight fallback parser.
    """
    env_candidates = (BASE_DIR.parent / '.env', BASE_DIR / '.env')
    env_path = next((p for p in env_candidates if p.exists()), None)
    if not env_path:
        return

    try:
        from dotenv import load_dotenv  # type: ignore
    except Exception:
        load_dotenv = None

    if load_dotenv:
        load_dotenv(env_path, override=False)
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#'):
            continue
        if line.startswith('export '):
            line = line[7:].strip()
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and (
            (value[0] == '"' and value[-1] == '"')
            or (value[0] == "'" and value[-1] == "'")
        ):
            value = value[1:-1]
        os.environ.setdefault(key, value)


def env_first(*names, default=''):
    for name in names:
        value = os.getenv(name)
        if value is not None and value != '':
            return value
    return default


def _load_secret_from_file(path_value):
    if not path_value:
        return ''

    secret_path = Path(path_value)
    if not secret_path.is_absolute():
        repo_path = BASE_DIR.parent / secret_path
        app_path = BASE_DIR / secret_path
        if repo_path.exists():
            secret_path = repo_path
        elif app_path.exists():
            secret_path = app_path

    try:
        return secret_path.read_text(encoding='utf-8').strip()
    except OSError:
        return ''


_load_env_file()

def env_list(name, default=''):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


def env_int(name, default):
    value = os.getenv(name)
    if value is None or value == '':
        return default
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _build_sqlite_db(path_value):
    path = path_value.strip() if path_value else ''
    if not path:
        return {'ENGINE': 'django.db.backends.sqlite3', 'NAME': BASE_DIR / 'db.sqlite3'}
    db_path = Path(path)
    if not db_path.is_absolute():
        db_path = BASE_DIR / db_path
    return {'ENGINE': 'django.db.backends.sqlite3', 'NAME': db_path}


def _database_from_url(db_url):
    if not db_url:
        return None

    parsed = urlparse(db_url)
    scheme = (parsed.scheme or '').lower()

    if scheme in {'postgres', 'postgresql', 'pgsql'}:
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': unquote((parsed.path or '/').lstrip('/')),
            'USER': unquote(parsed.username or ''),
            'PASSWORD': unquote(parsed.password or ''),
            'HOST': parsed.hostname or '127.0.0.1',
            'PORT': str(parsed.port or 5432),
            'CONN_MAX_AGE': env_int('DJANGO_DB_CONN_MAX_AGE', 60),
            'OPTIONS': {
                'sslmode': env_first('DJANGO_DB_SSLMODE', default='prefer'),
            },
        }

    if scheme in {'sqlite', 'sqlite3'}:
        sqlite_path = unquote(parsed.path or '')
        if parsed.netloc:
            sqlite_path = f"//{parsed.netloc}{sqlite_path}"
        if sqlite_path in {'', '/'}:
            return _build_sqlite_db('')
        if sqlite_path.startswith('/'):
            return {'ENGINE': 'django.db.backends.sqlite3', 'NAME': sqlite_path}
        return _build_sqlite_db(sqlite_path)

    return None


# Marketing analytics IDs (optional).
GA4_MEASUREMENT_ID = env_first(
    'GA4_MEASUREMENT_ID',
    'NEXT_PUBLIC_GA4_MEASUREMENT_ID',
    default='',
).strip()
YANDEX_METRIKA_COUNTER_ID = env_first(
    'YANDEX_METRIKA_COUNTER_ID',
    'YANDEX_METRIKA_ID',
    'YANDEX_METRICA_COUNTER_ID',
    default='',
).strip()
META_PIXEL_ID = env_first(
    'META_PIXEL_ID',
    'FACEBOOK_PIXEL_ID',
    default='',
).strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_first(
    'DJANGO_SECRET_KEY',
    default='django-insecure-*=p8h(5fcu=75c&r%1=m+st648f-@v%=%*cc+iplph(3+4^y_x'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', default=True)

# JaaS (Jitsi as a Service)
JAAAS_APP_ID = env_first('JAAAS_APP_ID', 'JAAS_APP_ID', default='')
JAAAS_KEY_ID = env_first('JAAAS_KEY_ID', 'JAAS_KEY_ID', default='')
JAAAS_PRIVATE_KEY = env_first('JAAAS_PRIVATE_KEY', 'JAAS_PRIVATE_KEY', default='').replace('\\n', '\n')
if not JAAAS_PRIVATE_KEY:
    JAAAS_PRIVATE_KEY = _load_secret_from_file(
        env_first('JAAAS_PRIVATE_KEY_FILE', 'JAAS_PRIVATE_KEY_FILE', default='')
    )
JAAAS_DOMAIN = env_first('JAAAS_DOMAIN', 'JAAS_DOMAIN', default='8x8.vc')
JAAAS_JWT_ISSUER = env_first('JAAAS_JWT_ISSUER', 'JAAS_JWT_ISSUER', default='chat')

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    default='localhost,127.0.0.1,.ngrok-free.app'
)
if DEBUG and '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('*')

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'chat', 
    'channels',
    'admin_interface',
    'colorfield',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'lessons',
    'main',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'maxschool.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'maxschool.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASE_URL = env_first('DATABASE_URL', default='').strip()
DB_SETTINGS_FROM_URL = _database_from_url(DATABASE_URL)

if DB_SETTINGS_FROM_URL:
    DATABASES = {'default': DB_SETTINGS_FROM_URL}
else:
    postgres_db = env_first('POSTGRES_DB', 'DJANGO_DB_NAME', default='').strip()
    if postgres_db:
        DATABASES = {
            'default': {
                'ENGINE': env_first('DJANGO_DB_ENGINE', default='django.db.backends.postgresql'),
                'NAME': postgres_db,
                'USER': env_first('POSTGRES_USER', 'DJANGO_DB_USER', default=''),
                'PASSWORD': env_first('POSTGRES_PASSWORD', 'DJANGO_DB_PASSWORD', default=''),
                'HOST': env_first('POSTGRES_HOST', 'DJANGO_DB_HOST', default='127.0.0.1'),
                'PORT': env_first('POSTGRES_PORT', 'DJANGO_DB_PORT', default='5432'),
                'CONN_MAX_AGE': env_int('DJANGO_DB_CONN_MAX_AGE', 60),
                'OPTIONS': {
                    'sslmode': env_first('DJANGO_DB_SSLMODE', default='prefer'),
                },
            }
        }
    else:
        DATABASES = {
            'default': _build_sqlite_db(
                env_first('DJANGO_SQLITE_PATH', default='db.sqlite3')
            )
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = env_first('DJANGO_TIME_ZONE', default='Asia/Yerevan')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.CustomUser'
AUTHENTICATION_BACKENDS = ['accounts.auth_backend.ApprovedTeacherBackend']

EMAIL_BACKEND = env_first(
    'DJANGO_EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = env_first('DJANGO_EMAIL_HOST', 'EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env_int('DJANGO_EMAIL_PORT', 587)
EMAIL_USE_TLS = env_bool('DJANGO_EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('DJANGO_EMAIL_USE_SSL', False)
EMAIL_TIMEOUT = env_int('DJANGO_EMAIL_TIMEOUT', 10)
EMAIL_HOST_USER = env_first('DJANGO_EMAIL_HOST_USER', 'EMAIL_HOST_USER', default='smarturok.ru@gmail.com')
EMAIL_HOST_PASSWORD = env_first('DJANGO_EMAIL_HOST_PASSWORD', 'EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env_first('DJANGO_DEFAULT_FROM_EMAIL', default=(EMAIL_HOST_USER or 'smarturok.ru@gmail.com'))
ADMIN_EMAIL = env_first('DJANGO_ADMIN_EMAIL', 'ADMIN_EMAIL', default='smarturok.ru@gmail.com')

X_FRAME_OPTIONS = env_first('DJANGO_X_FRAME_OPTIONS', default='DENY')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = env_bool('DJANGO_USE_X_FORWARDED_HOST', default=not DEBUG)

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', True)
    CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', True)
    SECURE_HSTS_SECONDS = env_int('DJANGO_SECURE_HSTS_SECONDS', 31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', True)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = env_first('DJANGO_SECURE_REFERRER_POLICY', default='strict-origin-when-cross-origin')

STATIC_URL = '/static/'

# Allow larger board state payloads (e.g. images on the whiteboard)
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20 MB
WHITEBOARD_WS_MAX_MESSAGE_BYTES = env_int('WHITEBOARD_WS_MAX_MESSAGE_BYTES', 2_500_000)
WHITEBOARD_WS_MAX_IMAGE_DATA_URL_LENGTH = env_int('WHITEBOARD_WS_MAX_IMAGE_DATA_URL_LENGTH', 1_500_000)
BOARD_STATE_MAX_REQUEST_BYTES = env_int('BOARD_STATE_MAX_REQUEST_BYTES', 6_000_000)
BOARD_STATE_MAX_SERIALIZED_BYTES = env_int('BOARD_STATE_MAX_SERIALIZED_BYTES', 6_000_000)
BOARD_STATE_MAX_BOARDS = env_int('BOARD_STATE_MAX_BOARDS', 40)
BOARD_STATE_MAX_IMAGE_DATA_URL_LENGTH = env_int('BOARD_STATE_MAX_IMAGE_DATA_URL_LENGTH', 1_500_000)

STATIC_ROOT = BASE_DIR / 'staticfiles'


STATICFILES_DIRS = [
    BASE_DIR / "static",
]

LOGIN_URL = '/accounts/login/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
ASGI_APPLICATION = 'maxschool.asgi.application'

# Канал-слой (в памяти)
REDIS_URL = env_first('REDIS_URL', default='').strip()
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        }
    }
#Если Redis доступен, например redis://127.0.0.1:6379/0
