# Generated by Django 5.2.1 on 2025-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacherapplication_customuser_desired_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видеосвязь'),
        ),
    ]
