# Generated by Django 5.2.1 on 2025-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='whiteboard_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на доску'),
        ),
    ]
