# Generated by Django 5.2.1 on 2025-07-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_lesson_whiteboard_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='whiteboard_url',
        ),
    ]
