# Generated by Django 5.2.1 on 2025-07-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_lesson_whiteboard_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True, null=True, verbose_name='Домашнее задание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии преподавателя'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема урока'),
        ),
    ]
