# Generated by Django 5.2.1 on 2025-08-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_lesson_homework_lesson_teacher_notes_lesson_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='homework_files/', verbose_name='Файл для ДЗ'),
        ),
    ]
