# Generated by Django 5.2.1 on 2025-08-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_lesson_homework_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student_homework_file',
            field=models.FileField(blank=True, null=True, upload_to='student_homework/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='student_homework_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
