# Generated by Django 5.2.1 on 2025-08-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_lesson_student_homework_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='student_homework_file',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='student_homework_text',
        ),
    ]
