# Generated by Django 5.2.1 on 2025-08-26 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_lesson_student_homework_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
