# Generated by Django 5.2.1 on 2025-08-26 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Закреплённые учителя'),
        ),
    ]
