# Generated by Django 5.2.1 on 2025-12-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='Если урок регулярный, указываем дни недели через запятую, например: Monday,Wednesday', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='homework_files/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
