# Generated by Django 5.2.11 on 2026-03-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialrequest',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialrequest',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialrequest',
            name='consent_user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trialrequest',
            name='personal_data_consent',
            field=models.BooleanField(default=False),
        ),
    ]
