# Generated by Django 5.2.11 on 2026-03-11 00:00

from django.db import migrations, models
from django.utils.text import slugify


def populate_subject_slugs(apps, schema_editor):
    Subject = apps.get_model('accounts', 'Subject')

    for subject in Subject.objects.all().order_by('id'):
        if subject.slug:
            continue

        base_slug = slugify(subject.name, allow_unicode=True) or f'subject-{subject.pk}'
        slug_candidate = base_slug
        suffix = 2
        while Subject.objects.exclude(pk=subject.pk).filter(slug=slug_candidate).exists():
            slug_candidate = f'{base_slug}-{suffix}'
            suffix += 1

        subject.slug = slug_candidate
        subject.save(update_fields=['slug'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_trialrequest_consent_at_trialrequest_consent_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='benefits',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='benefits_title',
            field=models.CharField(blank=True, default='Чему научится ученик', max_length=160),
        ),
        migrations.AddField(
            model_name='subject',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='hero_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='subject',
            name='landing_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='landing_image',
            field=models.ImageField(blank=True, null=True, upload_to='subjects/landing/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.TextField(blank=True, help_text='Каждый модуль с новой строки.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='program_title',
            field=models.CharField(blank=True, default='Программа обучения', max_length=160),
        ),
        migrations.AddField(
            model_name='subject',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subject',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.RunPython(populate_subject_slugs, noop_reverse),
    ]
