# Generated by Django 5.2.11 on 2026-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_subject_landing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='include_items',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='include_items_title',
            field=models.CharField(blank=True, default='Что входит в обучение', max_length=160),
        ),
        migrations.AddField(
            model_name='subject',
            name='metrics',
            field=models.TextField(
                blank=True,
                help_text='Каждая строка: Заголовок|Значение. Пример: Формат|Индивидуально 1:1',
            ),
        ),
        migrations.AddField(
            model_name='subject',
            name='progress_cards',
            field=models.TextField(blank=True, help_text='Каждая строка: Заголовок|Акцент|Описание.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='progress_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='progress_title',
            field=models.CharField(blank=True, default='Что меняется уже в первые 2-4 недели', max_length=160),
        ),
        migrations.AddField(
            model_name='subject',
            name='result_points',
            field=models.TextField(blank=True, help_text='Каждая строка: Заголовок|Описание.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='results_title',
            field=models.CharField(blank=True, default='Почему этот курс дает результат', max_length=160),
        ),
    ]
