# Generated by Django 5.2.11 on 2026-03-16 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_subject_sales_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Применено')),
                ('affected_lessons_count', models.PositiveIntegerField(default=0, verbose_name='Снято уроков')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vacations', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Отпуск ученика',
                'verbose_name_plural': 'Отпуска учеников',
                'ordering': ('-created_at',),
            },
        ),
    ]
