# Generated by Django 5.2.11 on 2026-03-27 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_request_workflow_sla_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Vacancy title')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Short description')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Responsibilities')),
                ('requirements', models.TextField(blank=True, verbose_name='Requirements')),
                ('conditions', models.TextField(blank=True, verbose_name='Conditions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.AlterModelOptions(
            name='teacherapplication',
            options={'ordering': ('-submitted_at',), 'verbose_name': 'Teacher application', 'verbose_name_plural': 'Teacher applications'},
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='years_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Experience years'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='experience',
            field=models.TextField(verbose_name='Experience details'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='motivation',
            field=models.TextField(verbose_name='Motivation'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='specialization',
            field=models.CharField(max_length=100, verbose_name='Subject/Specialization'),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accounts.vacancy', verbose_name='Vacancy'),
        ),
    ]
