# Generated by Django 5.2.11 on 2026-03-27 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_vacancy_alter_teacherapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherapplication',
            options={'ordering': ('-submitted_at',), 'verbose_name': 'Заявка преподавателя', 'verbose_name_plural': 'Заявки преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('order', 'title'), 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='experience',
            field=models.TextField(verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='motivation',
            field=models.TextField(verbose_name='Мотивация'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='specialization',
            field=models.CharField(max_length=100, verbose_name='Предмет/специализация'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accounts.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='years_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Опыт (лет)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=models.TextField(blank=True, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(blank=True, verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
    ]
