# Generated by Django 5.2.11 on 2026-03-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_teacherapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialrequest',
            name='promo_interest',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
