# Generated by Django 5.2.11 on 2026-05-09 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_materialtestattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('passing_score_percent', models.PositiveSmallIntegerField(default=70)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('show_correct_after_submit', models.BooleanField(default=True)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_options', models.BooleanField(default=False)),
                ('max_attempts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_bank', to='main.materialitem')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=40)),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('single', 'Single choice'), ('multiple', 'Multiple choice'), ('text', 'Text answer'), ('number', 'Number answer')], default='text', max_length=12)),
                ('points', models.PositiveIntegerField(default=1)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('explanation', models.TextField(blank=True, default='')),
                ('placeholder', models.CharField(blank=True, default='', max_length=160)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('correct_text', models.TextField(blank=True, default='', help_text='For text questions: one acceptable answer per line.')),
                ('correct_number', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('number_tolerance', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.materialtest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTestOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=140)),
                ('label', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.materialtestquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='materialtestquestion',
            index=models.Index(fields=['test', 'order'], name='main_mtq_test_order_idx'),
        ),
        migrations.AddIndex(
            model_name='materialtestquestion',
            index=models.Index(fields=['question_type', 'is_active'], name='main_mtq_type_act_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialtestquestion',
            constraint=models.UniqueConstraint(fields=('test', 'code'), name='main_mtq_test_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='materialtestoption',
            index=models.Index(fields=['question', 'order'], name='main_mto_q_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialtestoption',
            constraint=models.UniqueConstraint(fields=('question', 'value'), name='main_mto_q_val_uniq'),
        ),
    ]
